#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely, with a 2 second sleep gap between two iterations of the loop.
# It also displays "I am invincible!!!" when receiving a SIGTERM signal.

while 'true'
do
	echo "To infinity and beyond"
	sleep 2
	trap "{ echo 'I am invincible!!!'; }" SIGTERM
done
