#!/usr/bin/env bash
# This script displays numbers from 1 to 100.
# Requirements:
#	Displays FizzBuzz when the number is a multiple of 3 and 5
#	Displays Fizz when the number is multiple of 3
#	Displays Buzz when the number is a multiple of 5
#	Otherwise, displays the number
#	In a list format
counter=1
while [ $counter -le 100 ]
do
	div_3=$counter
	(( div_3 %= 3 ))

	div_5=$counter
	(( div_5 %= 5 ))

	if [ $div_3 -eq 0 ] && [ $div_5 -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $div_3 -eq 0 ]
	then
		echo "Fizz"
	elif [ $div_5 -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$counter"
	fi
	(( counter++ ))
done
