#!/usr/bin/env bash
# This script parses an Apache log file and groups visitors by IP and HTTP status code, and displays this data.
# The exact format must be:
#	OCCURENCE_NUMBER IP HTTP_CODE 
# Ordered from the greatest to the lowest number of occurrences.

awk '{split($0,a); print a[1],a[9]}' < apache-access.log | sort | uniq -c | sort -rn
