#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, but for the 9th iteration displays "Hi" on a newline after "Best School"
counter=1
while [ $counter -le 10 ]
do
	echo "Best School"
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	fi
	(( counter++ ))
done
