#!/usr/bin/env bash
# This script is displaying "bad luck" for 4th iteration, "good luck" for 8th iteration
# and "Best School" for the rest of the iterations from 1 to 10
counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]
	then
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( counter++ ))
done
