#!/usr/bin/env bash
# This script displays the contents of the current directory in a list format
# where only the part of the name after the first dash is displayed
var=$( find . -type f | cut -d '-' -f 2 )
for i in $var
do
	echo "$i"
done
