#!/usr/bin/env bash
# This script displays the contents of the current directory in a list format
# where only the part of the name after the first dash is displayed
for i in *
do
	var=$(echo "$i" | cut -d '-' -f 2)
	echo "$var"
done
